# https://taskfile.dev

version: '3'

vars:
  GOPROXY: 'https://goproxy.cn,direct'
  GOSUMDB: sum.golang.google.cn
  GOOS: $(go env GOOS)
  GOARCH: $(go env GOARCH)

tasks:

  gencopyright:
    desc: generate code license
    cmds:
      - go install github.com/google/addlicense@latest
      - hack/scripts/gencopyright.sh

  gofmt:
    cmds:
      - go install golang.org/x/tools/cmd/goimports@latest
      - gofmt -s -w .
      - goimports -w .

  govulncheck:
    desc: vulnerability detection
    cmds:
      - go install golang.org/x/vuln/cmd/govulncheck@v1.1.1
      - govulncheck ./...

  golint:
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.57.2
      - golangci-lint run -v ./...

  gci:
    cmds:
      - go install github.com/daixiang0/gci@v0.13.1
      - gci write --skip-generated --custom-order -s standard -s "prefix(github.com/easysoft/gitfox-webhooks)" -s default -s blank -s dot .

  gomod:
    cmds:
      - go mod tidy

  lint:
    desc: lint code
    cmds:
      - task: gomod
      - task: gofmt
      - task: gci
      # - task: golint
      - task: govulncheck

  fmt:
    desc: format code
    run: once
    cmds:
      - task: gencopyright
      - task: lint

  run:
    desc: debug run
    cmds:
      - go run ./example/example.go

  default:
    cmds:
      - task: fmt
      - task: run
